apiVersion: apps/v1
kind: Deployment
metadata:
  name: vibe-hub-deployment
  namespace: vibe-hub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vibe-hub
  template:
    metadata:
      name: vibe-hub-pod
      labels:
        app: vibe-hub
    spec:
      containers:
        - name: vibe-hub-container
          image: nginx:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: html-content
              mountPath: /usr/share/nginx/html
      volumes:
        - name: html-content
          configMap:
            name: html-content