apiVersion: v1
kind: Secret
metadata:
  name: git-ssh-key
  namespace: vibe-hub
type: Opaque
stringData:
  ssh: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
    QyNTUxOQAAACCS0wrB6H2ACIUL/eVpTZs5TRO2qoM8YqhaPNRUf31b2QAAAJDH5q3Nx+at
    zQAAAAtzc2gtZWQyNTUxOQAAACCS0wrB6H2ACIUL/eVpTZs5TRO2qoM8YqhaPNRUf31b2Q
    AAAEDwCI10SjG+txGEM8lWeBQ0yhGcOBPvUGqVsd8e0XOoe5LTCsHofYAIhQv95WlNmzlN
    E7aqgzxiqFo81FR/fVvZAAAACHZpYmUtaHViAQIDBAU=
    -----END OPENSSH PRIVATE KEY-----