apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cluster-coys-cluster
  namespace: argocd
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: SecretStore
    name: azure-keyvault
  target:
    name: cluster-coys-cluster
    creationPolicy: Owner
    template:
      type: Opaque
      metadata:
        labels:
          argocd.argoproj.io/secret-type: cluster
          bootstrap: "true"
          install-image-updater: "true"
          environment: dev
      data:
        name: "{{ .name }}"
        server: "{{ .server }}"
        config: "{{ .config }}"
  data:
    - secretKey: name
      remoteRef:
        key: argocd-coys-cluster-name
    - secretKey: server
      remoteRef:
        key: argocd-coys-cluster-server
    - secretKey: config
      remoteRef:
        key: argocd-coys-cluster-config
