apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: azure-keyvault
  namespace: argocd
spec:
  provider:
    azurekv:
      authType: WorkloadIdentity
      vaultUrl: https://aks-keyvault.vault.azure.net/
      serviceAccountRef:
        name: eso-azure-wi
