apiVersion: v1
kind: ServiceAccount
metadata:
  name: eso-azure-wi
  namespace: argocd
  annotations:
    azure.workload.identity/client-id: "REPLACE_WITH_UAMI_CLIENT_ID"
    azure.workload.identity/tenant-id: "REPLACE_WITH_TENANT_ID"
